config/routes.rb
Rails.application.routes.draw do

  mount API => '/'
  get 'admin'=>'admin/welcomes#index'
  namespace :admin do
    resources :categories
    resources :sub_categories
    resources :hot_categories
    resources :users
    resources :products
    resources :addresses
    resources :orders
    resources :units
    resources :adverts
    resources :detail_categories
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :address
  belongs_to :user

  def get_address
    address = self.address
    if address.present?
      address.area.to_s + address.detail.to_s
    else
      ""
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_order,only:[:edit,:update,:destroy]
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def update
    AppLog.info("params:   #{params[:order][:complete_time]}")
    if @order.update(order_params)
      AppLog.info("order.complete_time  #{@order.id}")
      redirect_to admin_orders_path
    else
      render 'edit' 
    end
  end

  def destroy
    @order.destroy
    redirect_to admin_orders_path
  end

  def create
    @order = Order.new(order_params)
    @order.unique_id = SecureRandom.urlsafe_base64
    if @order.save
      redirect_to admin_orders_path
    else
      render 'new'
    end
  end

  private 
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:state,:phone_num,:receive_name,:delivery_time,:address_id,:complete_time,:user_id)
    end
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
  def order_state
    [["请选择",""],["不可用",-1],["已生效",0],["送货中",1],["已完成",2],["已取消",3]]
  end

  def order_state_show(state)
    state_show = "暂无"
    case state
    when -1
      state_show = "不可用"
    when 0
      state_show = "已生效"
    when 1
      state_show = "送货中"
    when 2
      state_show = "已完成"
    when 3
      state_show = "已取消"
    end
    state_show
  end

end

app/views/admin/orders/_form.html.erb
<%= form_for([:admin,@order],html: {class: "form-horizontal", role: "form", multipart: true}) do |f| %>
  <div class ="form-group">
    <label class="col-sm-2 control-label">用户:</label>
    <div class="col-sm-4">
      <%= f.select :user_id, user_list,{},class: 'form-control'%>
    </div>
  </div>
  <div class ="form-group">
    <label class="col-sm-2 control-label">状态:</label>
    <div class="col-sm-4">
      <%= f.select :state, order_state,{},class: 'form-control'%>
    </div>
  </div>
  <div class ="form-group">
    <label class="col-sm-2 control-label">电话:</label>
    <div class="col-sm-4">
      <%= f.text_field :phone_num,class:"form-control"%>
    </div>
  </div>
  <div class ="form-group">
    <label class="col-sm-2 control-label">收货人名称:</label>
    <div class="col-sm-4">
      <%= f.text_field :receive_name,class:"form-control"%>
    </div>
  </div>
  <div class ="form-group">
    <label class="col-sm-2 control-label">发货时间:</label>
    <div class="col-sm-4">
      <%= f.text_field :delivery_time,class:"form-control"%>
    </div>
  </div>
  <div class ="form-group">
    <label class="col-sm-2 control-label">完成时间:</label>
    <div class="col-sm-4">
      <%= f.text_field :complete_time,class:"form-control"%>
    </div>
  </div>
  <div class ="form-group">
    <label class="col-sm-2 control-label">地址:</label>
    <div class="col-sm-4">
      <%= f.select :address_id, address_info,{},class: 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-4">
      <button calss="btn btn-success" type="submit">
        <span class="glyphicon glyphicon-floppy-save">保存</span>
      </button>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $("#order_delivery_time").datepicker({
    changeMonth: true,
    changeYear: true
  });
  $("#order_complete_time").datepicker({
    changeMonth: true,
    changeYear: true
  });
  $("#order_delivery_time" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
  $("#order_complete_time" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
  var delivery_time = '<%=@order.delivery_time%>'
  if(delivery_time != null && delivery_time != ""){
    $("#order_delivery_time" ).val(delivery_time)
  }
  var complete_time = '<%=@order.complete_time%>'
  if(complete_time != null && complete_time != ""){
    $("#order_complete_time" ).val(complete_time)
  }
</script>

app/views/admin/orders/edit.html.erb
<div class="col-sm-offset-3">
  <h2>编辑订单</h2>
</div>
<%= render 'form' %>

app/views/admin/orders/index.html.erb
<% content_for :title do %>
  订单列表
<% end %>
<h2 class="col-sm-offset-5">
   <a href = "/admin">订单列表</a>
</h2>
<div class="container">
  <%= link_to '添加订单', new_admin_order_path, class: ' btn btn-success'%>
  <% if @orders.present? %>
    <div class = "panel panel-default">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>id</th>
            <th>user_id</th>
            <th>state</th>
            <th>phone_num</th>
            <th>receive_name</th>
            <th>address</th>
            <th>products</th>
            <th>create_time</th>
            <th>delivery_time</th>
            <th>complete_time</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order|%>
            <tr>
              <td class="col-sm-1"><%=order.id%></td>
              <% if order.user.present? %>
                <td class="col-sm-1"><%=order.user.user_name%></td>
              <% else %>
                <td class="col-sm-1"></td>
              <% end %>
              <td class="col-sm-1"><%=order_state_show(order.state)%></td>
              <td class="col-sm-1"><%=order.phone_num%></td>
              <td class="col-sm-1"><%=order.receive_name%></td>
              <td class="col-sm-2"><%=address_show(order.address)%></td>
              <td class="col-sm-2"></td>
              <td class="col-sm-2"><%=time_show(order.created_at)%></td>
              <td class="col-sm-2"><%=time_show(order.delivery_time)%></td>
              <td class="col-sm-2"><%=time_show(order.complete_time)%></td>
              <td class="col-sm-2">
               <%= link_to '修改',edit_admin_order_path(order)%>|
               <%= link_to '删除', admin_order_path(order), method: :delete, data: { confirm: '确定要删除吗？' }%> 
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="col-sm-offset-2">
      <h2>赶快来添加吧！</h2>
    </div>
  <% end %>
</div>

app/views/admin/orders/new.html.erb
<div class="col-sm-offset-3">
  <h2>添加订单</h2>
</div>
<%= render 'form' %>