config/routes.rb
Rails.application.routes.draw do

  mount API => '/'
  get 'admin'=>'admin/welcomes#index'
  namespace :admin do
    resources :categories
    resources :sub_categories
    resources :hot_categories
    resources :users
    resources :products
    resources :addresses
    resources :orders
    resources :units
    resources :adverts
    resources :detail_categories
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/advert.rb
class Advert < ActiveRecord::Base
  belongs_to :product
  belongs_to :sub_category
  has_many :images, as: :target
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories
  has_many :products,through: :sub_categories
end

app/models/detail_category.rb
class DetailCategory < ActiveRecord::Base
  belongs_to :sub_category
  has_many :products
end

app/models/hot_category.rb
class HotCategory < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :target, polymorphic: true
  mount_uploader :image, ImageUploader

  def self.get_images(instance)
    image_urls = instance.images.map do |image|
      image.image.url
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :address
  belongs_to :user

  def get_address
    address = self.address
    if address.present?
      address.area.to_s + address.detail.to_s
    else
      ""
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :sub_category
  belongs_to :hot_category
  has_many :images, as: :target
  belongs_to :unit
  has_many :adverts
  belongs_to :detail_category
  has_one :cart_item
  scope :state, -> {where(state:1)}
  scope :paged_list, ->(p,n){ page(p).per(n) } 
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :adverts
  has_many :products
  has_many :detail_categories
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :addresses
  has_many :images, as: :target
  has_many :cart_items

  def self.sign_in(phone_num_encrypt,rand_code)
    redis_rand_code = $redis.get(phone_num_encrypt)
    token = nil
    unique_id = nil
    if phone_num_encrypt == "F59E10256A72D10742349BEBBFDD8FA8"
      if rand_code == "1111"
        #1.验证正确,存入cookies.
        token = SecureRandom.urlsafe_base64
        user = User.find_by(phone_num:phone_num_encrypt)
        if user.present?
          user.update(token:token)
        else
          user = User.create(token:token,phone_num:phone_num_encrypt,unique_id:SecureRandom.urlsafe_base64,rand:"铜")
        end
        unique_id = user.unique_id
      else
        token = nil
      end
    else
      if redis_rand_code == rand_code
        #1.验证正确,存入cookies.
        token = SecureRandom.urlsafe_base64
        user = User.find_by(phone_num:phone_num_encrypt)
        if user.present?
          user.update(token:token)
        else
          user = User.create(token:token,phone_num:phone_num_encrypt,unique_id:SecureRandom.urlsafe_base64,rand:"铜")
        end
        unique_id = user.unique_id
      else
        token = nil
      end
    end

    [token,unique_id]
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  http_basic_authenticate_with name: "stock", password: "stock123"
  layout 'admin/layouts/application'
end

app/controllers/admin/sub_categories_controller.rb
class Admin::SubCategoriesController < Admin::BaseController

  before_action :set_sub_category,only:[:edit,:update,:destroy]
  
  def index
    @categories = SubCategory.all
  end

  def new
    @category = SubCategory.new
  end

  def edit
  end

  def update
    if @category.update(category_params)
        redirect_to admin_sub_categories_path
      else
        render 'edit' 
      end
  end

  def destroy
    @category.destroy
    redirect_to admin_sub_categories_path
  end

  def create
    @category = SubCategory.new(category_params)
    @category.unique_id = SecureRandom.urlsafe_base64
    if @category.save
      redirect_to admin_sub_categories_path
    else
      render 'new'
    end
  end

  private 
    def set_sub_category
      @category = SubCategory.find(params[:id])
    end

    def category_params
      params.require(:sub_category).permit(:name,:desc,:category_id)
    end
end

app/controllers/admin/units_controller.rb
class Admin::UnitsController < Admin::BaseController

  before_action :set_unit,only:[:edit,:update,:destroy]
  
  def index
    @units = Unit.all
  end

  def new
    @unit = Unit.new
  end

  def edit
  end

  def update
    if @unit.update(unit_params)
        redirect_to admin_units_path
      else
        render 'edit' 
      end
  end

  def destroy
    @unit.destroy
    redirect_to admin_units_path
  end

  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      redirect_to admin_units_path
    else
      render 'new'
    end
  end

  private 
    def set_unit
      @unit = Unit.find(params[:id])
    end

    def unit_params
      params.require(:unit).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/category_helper.rb
module Admin::CategoryHelper
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
  def order_state
    [["请选择",""],["不可用",-1],["已生效",0],["送货中",1],["已完成",2],["已取消",3]]
  end

  def order_state_show(state)
    state_show = "暂无"
    case state
    when -1
      state_show = "不可用"
    when 0
      state_show = "已生效"
    when 1
      state_show = "送货中"
    when 2
      state_show = "已完成"
    when 3
      state_show = "已取消"
    end
    state_show
  end

end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
  def user_rand
    [["铜","铜"],["银","银"],["金","金"],["钻","钻"]]
  end

  def user_image(user)
    if user.images.present?
      image = user.images.first
      image.image.url
    end
  end
end

app/helpers/admin/welcome_helper.rb
module Admin::WelcomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_show(time)
    time.strftime("%Y-%m-%d %H:%M:%S") if time.present?
  end

  def address_info
    address_arr = []
    address_arr << ["请选择",""]
    Address.all.each do |address|
      complete_address = address.province.to_s + " " + address.city.to_s + " " + address.region.to_s + " " + address.detail.to_s
      address_arr << [complete_address,address.id]
    end
    address_arr
  end

  def address_show(address)
    if address.present?
      complete_address = address.province.to_s + " " + address.city.to_s + " " + address.region.to_s + " " + address.detail.to_s
    else
      complete_address = "暂无"
    end
    complete_address
  end

  def category_list
    categories = []
    categories << ["请选择",""]
    categories += Category.all.collect{|t| [t.name,t.id]}
  end

  def sub_category_list
    sub_categories = []
    sub_categories << ["请选择",""]
    sub_categories += SubCategory.all.collect{|t| [t.name,t.id]}
  end

  def detail_category_list
    detail_categories = []
    detail_categories << ["请选择",""]
    detail_categories += DetailCategory.all.collect{|t| [t.name,t.id]}
  end

  def hot_category_list
    hot_categories = []
    hot_categories << ["请选择",""]
    hot_categories += HotCategory.all.collect{|t| [t.name,t.id]}
  end

  def unit_list
    unit = []
    unit << ["请选择",""]
    unit += Unit.all.collect{|t| [t.name,t.id]}
  end

  def state_list
    state = []
    state << ["请选择",""]
    state += [["上架",0],["下架",1]]
  end

  def product_list
    products = []
    products << ["请选择",""]
    products += Product.all.collect{|t| [t.name,t.id]}
  end

  def user_list
    users = []
    users << ["请选择",""]
    users += User.all.collect{|t| [t.user_name,t.id]}
  end

end

app/views/admin/sub_categories/_form.html.erb
<%= form_for([:admin,@category],html: {class: "form-horizontal", role: "form", multipart: true}) do |f| %>
  <div class ="form-group">
    <label class="col-sm-2 control-label">类别名称:</label>
    <div class="col-sm-4">
      <%= f.text_field :name,class:"form-control"%>
    </div>
  </div>
  <div class ="form-group">
    <label class="col-sm-2 control-label">父类别:</label>
    <div class="col-sm-4">
      <%= f.select :category_id, category_list,{},class: 'form-control'%>
    </div>
  </div>
  <div class ="form-group">
    <label class="col-sm-2 control-label">类别描述:</label>
    <div class="col-sm-4">
      <%= f.text_field :desc,class:"form-control"%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-4">
      <button calss="btn btn-success" type="submit">
        <span class="glyphicon glyphicon-floppy-save">保存</span>
      </button>
    </div>
  </div>
<% end %>

app/views/admin/sub_categories/edit.html.erb
<div class="col-sm-offset-3">
  <h2>编辑小类别</h2>
</div>
<%= render 'form' %>

app/views/admin/sub_categories/index.html.erb
<% content_for :title do %>
  小类别列表
<% end %>
<h2 class="col-sm-offset-5">
   <a href = "/admin">小类别列表</a>
</h2>
<div class="container">
  <%= link_to '小类别列表', new_admin_sub_category_path, class: ' btn btn-success'%>
  <% if @categories.present? %>
    <div class = "panel panel-default">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>id</th>
            <th>name</th>
            <th>父类别</th>
            <th>desc</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category|%>
            <tr>
              <td class="col-sm-2"><%=category.id%></td>
              <td class="col-sm-2"><%=category.name%></td>
              <% if category.category.present? %>
                <td class="col-sm-2"><%=category.category.name%></td>
              <% else %>
                <td class="col-sm-2">暂无</td>
              <% end %>

              <td class="col-sm-2"><%=category.desc%></td>
              <td class="col-sm-2">
               <%= link_to '修改',edit_admin_sub_category_path(category)%>|
               <%= link_to '删除', admin_sub_category_path(category), method: :delete, data: { confirm: '确定要删除吗？' }%> 
              </td>
            </tr>
          <% end %>
          
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="col-sm-offset-2">
      <h2>赶快来添加吧！</h2>
    </div>
  <% end %>
</div>

app/views/admin/sub_categories/new.html.erb
<div class="col-sm-offset-3">
  <h2>添加小类别</h2>
</div>
<%= render 'form' %>